version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"   

  logstash:
    build:
      context: logstash/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"      
    depends_on:
      - elasticsearch